name: meditation_app
version: 1.0.0+1
description: A new Flutter project.
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.2.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  flutter_vector_icons: ^2.0.0
  get: ^4.6.5
  google_sign_in: ^5.4.2
  iconsax: ^0.0.8
  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/ballet.jpeg
    - assets/images/ballet1.jpeg
    - assets/images/ballet2.jpeg
    - assets/images/contem.jpeg
    - assets/images/contem1.jpeg
    - assets/images/contem2.jpeg
    - assets/images/contemporary.jpg
    - assets/images/hiphop.jpeg
    - assets/images/hiphop.png
    - assets/images/hiphop2.jpg
    - assets/images/
    - assets/images/login.png
    - assets/images/register.png
  fonts:
    - family: harlow-solid-italic
      fonts:
        - asset: assets/fonts/harlow-solid-italic/harlow-solid-italic.ttf
        - asset: assets/fonts/monday-feelings-font/MondayFeelings-7BD2l.ttf
  uses-material-design: true
