// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqP-fKbe2N-CtymDu47oNfkLArByOb5s',
    appId: '1:419864568094:web:769df3b69aeb51377da90f',
    messagingSenderId: '419864568094',
    projectId: 'musvenfit',
    authDomain: 'musvenfit.firebaseapp.com',
    storageBucket: 'musvenfit.appspot.com',
    measurementId: 'G-3B7753CVR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH82QE4f3bCPCEAUz6yFtiypurNLAb41E',
    appId: '1:419864568094:android:8159859ac92a36147da90f',
    messagingSenderId: '419864568094',
    projectId: 'musvenfit',
    storageBucket: 'musvenfit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcu8Ad5LGFiOjiGp7bMbUygoJW7Ztv1Zw',
    appId: '1:419864568094:ios:2389a1df5507887d7da90f',
    messagingSenderId: '419864568094',
    projectId: 'musvenfit',
    storageBucket: 'musvenfit.appspot.com',
    androidClientId: '419864568094-ajp9ere0uf2mqp5t7vr04p0lvio4k6ek.apps.googleusercontent.com',
    iosClientId: '419864568094-1qno3hunb7h2841vjs9e5sc3e4qsde25.apps.googleusercontent.com',
    iosBundleId: 'com.example.musvenfitProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcu8Ad5LGFiOjiGp7bMbUygoJW7Ztv1Zw',
    appId: '1:419864568094:ios:2389a1df5507887d7da90f',
    messagingSenderId: '419864568094',
    projectId: 'musvenfit',
    storageBucket: 'musvenfit.appspot.com',
    androidClientId: '419864568094-ajp9ere0uf2mqp5t7vr04p0lvio4k6ek.apps.googleusercontent.com',
    iosClientId: '419864568094-1qno3hunb7h2841vjs9e5sc3e4qsde25.apps.googleusercontent.com',
    iosBundleId: 'com.example.musvenfitProject',
  );
}
